(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: industrialPhysics_2.4.master                                 *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.10491.master                                             *)
(*        Build: 164f85bec                                                    *)
(*         Date: 2020-03-30, Time: 13:49:25                                   *)
(*                                                                            *)

TYPE
ComTCP_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 15;

        Emergency_Button_ButtonToggle : BOOL := 0;
        (* BOOL Emergency_Button_ButtonToggle *)
        Yellow_Button_ButtonPress : BOOL := 0;
        (* BOOL Yellow_Button_ButtonPress *)
        White_Button_ButtonPress : BOOL := 0;
        (* BOOL White_Button_ButtonPress *)
        Start_Button_ButtonPress : BOOL := 0;
        (* BOOL Start_Button_ButtonPress *)
        Stop_Button_ButtonPress : BOOL := 0;
        (* BOOL Stop_Button_ButtonPress *)
        Knob_0_AXIS : REAL := 0.0;
        (* REAL Knob_0_AXIS *)
        Knob_1_AXIS : REAL := 0.0;
        (* REAL Knob_1_AXIS *)
        Knob_2_AXIS : REAL := 0.0;
        (* REAL Knob_2_AXIS *)
        Knob_3_AXIS : REAL := 0.0;
        (* REAL Knob_3_AXIS *)
        Shaft_1_AXIS : REAL := 0.0;
        (* REAL Shaft_1_AXIS *)
        Shaft_1_LBK : BOOL := 0;
        (* BOOL Shaft_1_LBK *)
        Shaft_1_LFR : BOOL := 0;
        (* BOOL Shaft_1_LFR *)
        Shaft_0_AXIS : REAL := 0.0;
        (* REAL Shaft_0_AXIS *)
        Shaft_0_LBK : BOOL := 0;
        (* BOOL Shaft_0_LBK *)
        Shaft_0_LFR : BOOL := 0;
        (* BOOL Shaft_0_LFR *)

	END_STRUCT;

ComTCP_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 6;

        Yellow_light_Key : UDINT := 0;
        (* UDINT Yellow_light_Key *)
        Stop_light_Key : UDINT := 0;
        (* UDINT Stop_light_Key *)
        White_light_Key : UDINT := 0;
        (* UDINT White_light_Key *)
        Green_light_Key : UDINT := 0;
        (* UDINT Green_light_Key *)
        Shaft_0_ACT_POS : REAL := 0.0;
        (* REAL Shaft_0_ACT_POS *)
        Shaft_1_ACT_POS : REAL := 0.0;
        (* REAL Shaft_1_ACT_POS *)

	END_STRUCT;


END_TYPE
